// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jin.roo2.repository;

import com.jin.roo2.repository.FoodRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FoodRepository_Roo_Jpa_Repository {
    
    declare @type: FoodRepository: @Transactional(readOnly = true);
    
}
